---
format: html
editor: visual
execute:
  eval: false
---

[Hands-on sessions](index.html) / [Hands-on session 2](exercise_session_2.html) /

```{=html}
  <div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
🤓 Challenge
</div>
</div>
<div class="callout-body-container callout-body">
<p>Create an image of an animal that is a cross between two different real animals. Save it as a file and post it in <a href="https://scilifelab.slack.com/archives/C078U8VL10R">the Slack channel for this session</a>. We will demo the submissions on the big screen.</p>
</div>
</div>
```
## Image generation

One use of LLMs that has become popular is image generation. The version of Microsoft Copilot available via the universities can create images. The free version of ChatGPT does not offer full image generation capability but you can try and see what it gives you 😀.

Some example prompts:

```{r}
An astronaut standing on the moon looking at Earth.
```

```{r}
A futuristic city with sleek, glass-covered skyscrapers, flying cars zipping through the air, and digital billboards flashing with vibrant colors.
```

```{r}
An illustration of the water cycle, showing evaporation, condensation, precipitation, and collection.
```
