---
title: "Hands-on with Large Language Models: Exercises"
format: html
editor: visual
---

Welcome to the hands-on sessions for the workshop "Hands-on with Large Language Models". Select the hands-on session and you will see further guiding on the following page. Questions? Ask us!

## Preparation

You need to have access to a Large Language Model (LLM) tool to do the exercises. If you never tried an LLM this is your time! Head to Microsoft Copilot if your university provides that, below we collected details for each university. Otherwise feel free to use any other LLM tool, for example [ChatGPT](https://chat.openai.com/) (OpenAI, USA) or [Mistral Le Chat](https://mistral.ai/) (French company).

Select your university for instructions on how to access Microsoft Copilot:

-   Chalmers University of Technology: [Instructions for access to Microsoft Copilot](https://guides.lib.chalmers.se/sokaochutvarderainformation/EN/ai)
-   Karolinska Institute: [Instructions for access to Microsoft Copilot](https://staff.ki.se/tools-and-support/it-and-telephony/it-research-support/ai-for-staff-bing-chat-enterprise)
-   KTH Royal Institute of Technology: no LLM available, use ChatGPT, Mistral or another.
-   Linköping University: [Instructions for access to Microsoft Copilot](https://liu.se/en/news-item/liu-far-copilot)
-   Lund University: [Instructions for access to Microsoft Copilot](https://www.staff.lu.se/article/lu-employees-can-now-use-ai-assistant-copilot-former-bing-chat-free)
-   Stockholm University: no LLM available, use ChatGPT, Mistral or another.
-   Swedish University of Agricultural Sciences: no LLM available, use ChatGPT, Mistral or another.
-   Umeå University: [Instructions for access to Microsoft Copilot](https://manual.its.umu.se/en/how-to-use-bing-chat/)
-   University of Gothenburg: [Instructions for access to Microsoft Copilot](https://studentportal.gu.se/en/news/you-can-now-login-with-your-student-account-to-use-copilot-with-bing)
-   Uppsala University: [Instructions for access to Microsoft Copilot](https://www.uu.se/en/staff/service-and-tools/tools-and-guides/generate-and-process-texts-and-images-using-ai/log-in-to-copilot)

## Hands-on sessions

### [Hands-on session 1 -\>](exercise_session_1.html)

### [Hands-on session 2 -\>](exercise_session_2.html)
